// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  breve.Examples.BraitenbergVehicle = (function(_super) {

    __extends(BraitenbergVehicle, _super);

    function BraitenbergVehicle() {
      return BraitenbergVehicle.__super__.constructor.apply(this, arguments);
    }

    BraitenbergVehicle.prototype.setup = function(attrs) {
      BraitenbergVehicle.__super__.setup.call(this, attrs);
      this.set("location", breve.vector([250, 250]));
      this.set("radius", 80);
      this.set("image", "images/car.png");
      this.leftSensor = this.addChild(new breve.Examples.BraitenbergSensor(this.engine, {
        location: [65, -25]
      }));
      return this.rightSensor = this.addChild(new breve.Examples.BraitenbergSensor(this.engine, {
        location: [65, 25]
      }));
    };

    BraitenbergVehicle.prototype.step = function(step) {
      BraitenbergVehicle.__super__.step.call(this, step);
      this.set("heading", this.get('heading') + 0.02);
      return this.set("velocity", breve.vector([10, 0]).rotate(this.get('heading'), [0, 0]));
    };

    return BraitenbergVehicle;

  })(breve.Agent);

  breve.Examples.BraitenbergSensor = (function(_super) {

    __extends(BraitenbergSensor, _super);

    function BraitenbergSensor() {
      return BraitenbergSensor.__super__.constructor.apply(this, arguments);
    }

    BraitenbergSensor.prototype.setup = function(attrs) {
      BraitenbergSensor.__super__.setup.call(this, attrs);
      this.set("radius", 6);
      return this.set("color", [1, 1, 1, 1]);
    };

    return BraitenbergSensor;

  })(breve.Agent);

  breve.Examples.BraitenbergLight = (function(_super) {

    __extends(BraitenbergLight, _super);

    function BraitenbergLight() {
      return BraitenbergLight.__super__.constructor.apply(this, arguments);
    }

    BraitenbergLight.prototype.setup = function(attrs) {
      BraitenbergLight.__super__.setup.call(this, attrs);
      this.set("radius", 4);
      return this.set("color", [.5, 0, 0, 1]);
    };

    return BraitenbergLight;

  })(breve.Agent);

}).call(this);
